version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gstcgstc
      POSTGRES_DB: deberSeguro
    ports:
      - '5433:5432'

  app:
    image: deber-seguro
    ports:
      - 3000:3000